silverstripe/silverstripe-tagfield

js/TagField.js
Sometimes Select2 is not bound to jQuery yet which results in the field not being displayed. I've also added back in the `.show()` which I removed last PR. It needs to be there otherwise Select2 evaluates the `select` width incorrectly.
=> Fix race condition with Select2

css/TagField.css
=> Correct close button image

.travis.yml, code/TagField.php, composer.json, js/TagField.js, tests/unit/TagFieldTest.php, tests/unit/TagFieldTest.yml
=> Added tests and extra ajax functionality

README.md
=> Minor: TagField typo in readme

README.md
New silverstripe funcitonality of create and chaining to be highlighted in the example
=> examples using create and chaining

README.md
Fixed incorrect StringTagField documentation example.
=> StringTagField documentation fix

js/TagField.js
'Chosen' plugin assumed, but on front-end this is not
a valid assumption.
=> BUGFIX: Allow use on frontend

README.md
Updating read me example code with little fixes such as:
* Making `static` variables `private static`
* Incorrect `$post->BlogTags()` call changed to `$this->BlogTags()`
* Alignment of comments
=> Little fixes to read me example code.

code/StringTagField.php
=> Override DropdownField::validate() in StringTagField

code/StringTagField.php
Fixed previously merged PR.
See - https://github.com/silverstripe-labs/silverstripe-tagfield/pull/48#event-430875069
=> FIX: Removed duplicate setAttribute('multiple')

code/TagField.php
sorry, I didn't realize there are 2 fields.
=> Added missing $isMultiple

code/StringTagField.php, code/TagField.php, css/TagField.css, tests/TagFieldTest.php
BUG Fix isMultiple not being initialised
BUG Fix tag rendering as a 100px wide container
=> BUG Fix duplicate tag creation

tests/TagFieldTest.php
Fixes the tests that rely on tags having specific IDs
=> FIX Tests with hard coded IDs

code/StringTagField.php, code/TagField.php, js/TagField.js
=> Apply canCreate permissions to Select2 for tags

src/StringTagField.php
Fixes https://github.com/silverstripe/silverstripe-tagfield/issues/96
=> declaring allowed actions as private as per RequestHandler

src/ReadonlyTagField.php, src/StringTagField.php, src/TagField.php, tests/TagFieldTest.php
Issues are reported here https://github.com/silverstripe/silverstripe-tagfield/issues/99
=> Fixed performReadonlyTransformation

css/TagField.css, js/TagField.js, src/TagField.php, tests/TagFieldTest.php
This contains bits of CSS and JS updates so that the tag fields looks similar to the ListBox fields and other fields in the CMS.
=> Tag field to look similar to list field

src/TagField.php
* Added parameter to SilverStripe\TagFieldTagField::__construct()
* Modified SilverStripe\TagFieldTagField::getOptions() to use assigned title field
* Modified SilverStripe\TagFieldTagField::getValue() to use assigned title field
=> Set "title field" at a meaningful point in TagField instantiation

_config/config.yml, src/StringTagField.php, src/TagField.php
* Add yaml file
* Remove requirement calls from field constructors
=> Add css and js to left and main

client/src/boot/registerComponents.js
#74 Should help fix the last mentioned error.
=> Update faulty import of TagField component
